# Sankofa Integration Configuration
# Defines how this knowledge base integrates with Sankofa privacy layer

sankofa_integration:
  version: "1.0.0"
  compatibility: "sankofa-v1.x"
  
  # Import Configuration
  import:
    supported_formats:
      - "sankofa_bundle"      # Standard Sankofa export format
      - "sankofa_stream"      # Real-time streaming format
      - "sankofa_archive"     # Historical data archive
    
    data_mapping:
      # Map Sankofa data types to knowledge base content types
      sankofa_personal_note: "note"
      sankofa_task_item: "todo" 
      sankofa_calendar_event: "calendar"
      sankofa_journal_entry: "journal"
      sankofa_project_data: "project"
      sankofa_reference_material: "reference"
    
    privacy_preservation:
      maintain_deidentification: true
      preserve_sankofa_metadata: true
      respect_privacy_levels: true
      
    processing_rules:
      # How to handle de-identified data
      - "Preserve all Sankofa privacy tokens"
      - "Maintain context relationships without re-identification"
      - "Generate new organizational metadata while preserving privacy"
      - "Create cross-references using privacy-safe identifiers"

  # Export Configuration  
  export:
    target_formats:
      - "sankofa_bundle"      # For re-import to Sankofa
      - "sankofa_portable"    # For USB keychain storage
      - "sankofa_sync"        # For device synchronization
    
    data_enrichment:
      # What organizational data to add back to Sankofa
      include_tags: true
      include_categories: true
      include_cross_references: true
      include_ai_insights: true
      include_connection_graph: true
    
    privacy_compliance:
      strip_identifying_metadata: true
      validate_deidentification: true
      maintain_sankofa_format: true

  # Real-time Integration
  streaming:
    enabled: true
    modes:
      - "live_processing"     # Process data as it comes from Sankofa
      - "batch_sync"         # Periodic synchronization
      - "event_driven"       # Triggered by specific events
      - "universal_mode"     # Sankofa works standalone with any AI/app
    
    processing_pipeline:
      1. "receive_deidentified_data"
      2. "validate_privacy_preservation" 
      3. "extract_knowledge_components"
      4. "organize_and_categorize"
      5. "create_connections"
      6. "update_search_indexes"
      7. "generate_insights"
      8. "prepare_export_format"

  # AI Tool Integration  
  ai_interface:
    output_modes:
      # Default mode optimized for AI consumption
      default_mode: "ai_optimized"
      
      # AI-Optimized mode (primary use case)
      ai_optimized:
        token_style: "bracketed"          # [PHYSICIAN], [CONDITION]
        include_metadata: true            # Rich context bundle
        include_relationships: true       # Cross-domain connections
        preserve_temporal: true           # Keep non-sensitive dates/times
        
      # Human-Readable mode (documents, emails)
      human_readable:
        generalization_style: "natural"   # "my doctor", "medical condition"
        preserve_readability: true        # Maintain natural flow
        minimal_tokens: true              # Avoid [BRACKETS] in text
        
      # Hybrid mode (collaborative work)
      hybrid:
        selective_tokenization: true      # Only highly sensitive data
        context_aware: true               # Adjust based on recipient
        
    query_handling:
      # How AI tools should process Sankofa output
      understand_tokens: true             # AI knows [TOKEN] = sensitive data
      use_metadata_context: true          # Leverage rich metadata
      maintain_privacy_boundaries: true   # Never attempt re-identification
    
    response_optimization:
      # Enhance AI responses using privacy-safe context
      leverage_metadata: true             # Use context for better responses
      suggest_follow_ups: true            # Generate relevant next actions
      maintain_domain_context: true       # Keep healthcare, work, personal separate

  # Security and Compliance
  security:
    encryption_at_rest: true
    secure_transfer_protocols: true
    audit_logging: true
    access_controls: true
    
  compliance:
    hipaa_compatible: true
    gdpr_compliant: true
    sankofa_certified: true

# Plugin Architecture for Sankofa
plugins:
  sankofa_importer:
    enabled: true
    auto_detect_format: true
    validation_rules: "strict"
  
  sankofa_exporter:
    enabled: true
    format_optimization: true
    compression: true
  
  privacy_validator:
    enabled: true
    real_time_checking: true
    alert_on_violations: true

# Workflow Templates
workflows:
  daily_sync:
    - "import_new_sankofa_data"
    - "process_and_organize"
    - "update_connections"
    - "export_enriched_data"
    - "sync_back_to_sankofa"
  
  knowledge_discovery:
    - "analyze_connection_patterns"
    - "identify_knowledge_gaps"
    - "suggest_new_connections"
    - "generate_insights_report"
  
  portable_export:
    - "compile_complete_knowledge_base"
    - "validate_privacy_compliance"
    - "optimize_for_portability"
    - "create_sankofa_bundle" 